"""add assigned_to to incidents

Revision ID: c06529486ad5
Revises: 9f8609606ed0
Create Date: 2026-07-21 08:06:37.959618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c06529486ad5'
down_revision: Union[str, Sequence[str], None] = '9f8609606ed0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incidents', sa.Column('assigned_to', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'incidents', 'users', ['assigned_to'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'incidents', type_='foreignkey')
    op.drop_column('incidents', 'assigned_to')
    # ### end Alembic commands ###
